"""Compare memberships and factorial invariants; do not select a preferred method."""
from pathlib import Path
import pandas as pd,numpy as np,json,hashlib
from scipy.optimize import linear_sum_assignment
from sklearn.metrics import adjusted_rand_score
D=Path(__file__).resolve().parents[1];R=D.parent;checks=[]
def check(label,ok,detail=None):
 checks.append({'check':label,'passed':bool(ok),'detail':detail});print(('PASS ' if ok else 'FAIL ')+label,flush=True)
def read(run,rel):return pd.read_csv(D/run/rel)
def sig(t):return t[(t.q_value<.05)&(t.n_agree==t.n_studies)]
def same_stats(a,b):
 a=a.set_index('ensembl_id').sort_index();b=b.set_index('ensembl_id').sort_index();return a.index.equals(b.index) and all(np.allclose(a[c],b[c],atol=1e-12,rtol=1e-8,equal_nan=True) for c in ['median_rho','q_value','combined_p','n_studies','n_agree'])
runs=['baseline','labels_only','normalisation_only','combined'];fib={r:read(r,'data/progression_full/progression_fibrosis.csv') for r in runs};dis={r:read(r,'data/progression_full/progression_disease.csv') for r in runs};cl={r:read(r,'Paper1_Results/Task2/task2_gene_clusters.csv') for r in runs};master={r:read(r,'Paper1_HighConfidence/01_master_table.csv') for r in runs};short={r:read(r,'Paper1_HighConfidence/11_FINAL_shortlist_25_genes.csv') for r in runs};basefib=set(sig(fib['baseline']).ensembl_id);basedis=set(sig(dis['baseline']).ensembl_id);baseshort=set(short['baseline'].Ensembl_ID);basetier=set(master['baseline'].loc[master['baseline'].HighConfidenceScore>=7,'ensembl_id'])
check('Label-only changes leave fibrosis discovery unchanged',same_stats(fib['baseline'],fib['labels_only']));check('Normalisation-only changes leave disease discovery unchanged',same_stats(dis['baseline'],dis['normalisation_only']));check('Disease discovery matches between labels-only and combined',same_stats(dis['labels_only'],dis['combined']));check('Fibrosis discovery matches between normalisation-only and combined',same_stats(fib['normalisation_only'],fib['combined']))
check('Baseline matches active discovery',same_stats(fib['baseline'],pd.read_csv(R/'data/progression_full/progression_fibrosis.csv')) and same_stats(dis['baseline'],pd.read_csv(R/'data/progression_full/progression_disease.csv')));check('Baseline shortlist matches active shortlist',baseshort==set(pd.read_csv(R/'Paper1_HighConfidence/11_FINAL_shortlist_25_genes.csv').Ensembl_ID))
basecent=cl['baseline'].groupby('cluster')[['F0','F1','F2','F3','F4']].mean().to_numpy();summary=[];details={};genes=[];network_rows=[]
for r in runs:
 fs=set(sig(fib[r]).ensembl_id);ds=set(sig(dis[r]).ensembl_id);t1=set(master[r].loc[master[r].HighConfidenceScore>=7,'ensembl_id']);ss=set(short[r].Ensembl_ID);common=cl['baseline'][['ensembl_id','cluster']].merge(cl[r][['ensembl_id','cluster']],on='ensembl_id',suffixes=('_base','_run'));ari=float(adjusted_rand_score(common.cluster_base,common.cluster_run));cent=cl[r].groupby('cluster')[['F0','F1','F2','F3','F4']].mean().to_numpy();corr=np.corrcoef(basecent,cent)[:5,5:];a,b=linear_sum_assignment(-corr);shape={f'C{j+1}':{'mapped_to_baseline':f'C{i+1}','correlation':float(corr[i,j])} for i,j in zip(a,b)}
 confident=cl[r][cl[r].membership_confidence>=.8];finaltier=read(r,'Paper1_HighConfidence/11_final_tier1_genes.csv');strength=int((finaltier['LOSO_still_strong_rho0.30_of_5']==5).sum());signif=int((finaltier.LOSO_still_significant_of_5==5).sum());ab=json.loads((D/r/'F_ablation/ablation_config.json').read_text());abshort=read(r,'F_ablation/11_FINAL_shortlist_25_genes.csv');abset=set(abshort.Ensembl_ID)
 summary.append({'run':r,'fibrosis_genes':len(fs),'disease_genes':len(ds),'shared':len(fs&ds),'union':len(fs|ds),'fibrosis_added':len(fs-basefib),'fibrosis_removed':len(basefib-fs),'disease_added':len(ds-basedis),'disease_removed':len(basedis-ds),'Tier1':len(t1),'Tier1_retained_from_baseline':len(t1&basetier),'shortlist_size':len(ss),'shortlist_retained_from_baseline':len(ss&baseshort),'cluster_ARI_common_genes':round(ari,4),'confident_cluster_genes':len(confident),'Tier1_LOSO_significant_all5':signif,'Tier1_LOSO_strong_all5':strength,'F_ablation_Tier1':ab['tier1_genes'],'F_ablation_shortlist_size':ab['shortlist_genes'],'F_ablation_baseline_shortlist_retained':len(abset&baseshort),'F_ablation_own_shortlist_retained':len(abset&ss)})
 details[r]={'fibrosis_added':sorted(fs-basefib),'fibrosis_removed':sorted(basefib-fs),'disease_added':sorted(ds-basedis),'disease_removed':sorted(basedis-ds),'shortlist_added':sorted(set(short[r].Gene)-set(short['baseline'].Gene)),'shortlist_removed':sorted(set(short['baseline'].Gene)-set(short[r].Gene)),'centroid_matching':shape,'F_ablation':ab}
 check(r+' cluster membership matches discovery',set(cl[r].ensembl_id)==fs and not cl[r].ensembl_id.duplicated().any());availability=master[r].loc[master[r].HighConfidenceScore>=7].groupby('cluster').size().reindex(sorted(master[r].cluster.unique()),fill_value=0);shortcounts=short[r].groupby('Cluster').size().reindex(availability.index,fill_value=0);check(r+' main shortlist meets unrelaxed quota',len(ss)==len(short[r]) and shortcounts.equals(availability.clip(upper=5)) and set(ss)<=t1);details[r]['main_Tier1_available_per_cluster']=availability.to_dict();details[r]['main_shortlist_shortages']=[k for k,v in availability.items() if v<5];loso=read(r,'Paper1_HighConfidence/10_loso_all_eligible_runs.csv');check(r+' LOSO uses full universe in five fits',len(loso)==14794*5 and loso.left_out.nunique()==5)
 clin=read(r,'data/graph/nodes_sample_clinical.csv');check(r+' same 610 staged patients',clin[clin.fibrosis_stage.notna()].patient_id.nunique()==610)
 for mode,frame in [('standard',short[r]),('without_F',abshort)]:
  for _,row in frame.iterrows():genes.append({'run':r,'scoring':mode,'Gene':row['Gene'],'ensembl_id':row['Ensembl_ID'],'cluster':row['Cluster'],'score':row['Total_score'],'direction':row['Direction'],'LOSO_significant_of5':row['LOSO_still_significant_of_5'],'LOSO_strong_of5':row['LOSO_still_strong_rho0.30_of_5']})
  sub='Paper1_HighConfidence' if mode=='standard' else 'F_ablation';wb=pd.read_excel(D/r/sub/'12_KG_supplementary.xlsx',sheet_name=None);edge=wb['4_figure_edges'];ranking=wb['3_all_mechanisms_ranked'];selected=ranking[ranking.selected_for_figure];network_rows.append({'run':r,'scoring':mode,'selected_mechanisms':len(selected),'displayed_genes':edge.Ensembl_ID.nunique(),'edges':len(edge),'shortlisted_genes_shown':edge.loc[edge.In_final_25,'Ensembl_ID'].nunique()});selected.assign(run=r,scoring=mode).to_csv(D/f'{r}_{mode}_selected_mechanisms.csv',index=False)
 # Input changes are exactly the declared perturbations.
 clinical=pd.read_csv(R/'data/graph/nodes_sample_clinical.csv',dtype=str).fillna('');current=clin.fillna('');fields=['sample_id','dataset_id','patient_id','biopsy_number','fibrosis_stage','fibrosis_stage_raw','disease_group_raw'];
 for f in fields:check(r+' preserves clinical '+f,list(current[f].astype(str).str.replace(r'\.0$','',regex=True))==list(clinical[f].astype(str).str.replace(r'\.0$','',regex=True)))
changes=[]
for p,h in json.loads((D/'active_baseline_hashes.json').read_text()).items():
 if hashlib.sha256((R/p).read_bytes()).hexdigest()!=h:changes.append(p)
check('Active package/results/code preserved',not changes,changes)
pd.DataFrame(summary).to_csv(D/'comparison_summary.csv',index=False);pd.DataFrame(genes).to_csv(D/'shortlist_comparison.csv',index=False);pd.DataFrame(network_rows).to_csv(D/'network_comparison.csv',index=False);(D/'membership_and_cluster_details.json').write_text(json.dumps(details,indent=2));(D/'verification_results.json').write_text(json.dumps(checks,indent=2));assert all(c['passed'] for c in checks);print(pd.DataFrame(summary).to_string(index=False))
