"""Build an evidence plan for the promoted package without drafting manuscript prose."""
from pathlib import Path
import csv,json,hashlib
import pandas as pd
R=Path(__file__).resolve().parents[1];OUT=R/'manuscript_planning';OUT.mkdir(exist_ok=True);P=R/'Paper1_Package';docs=R/'docs/package'
records=[]
for p in sorted(P.rglob('*')):
 if not p.is_file():continue
 rec={'file':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
 if p.suffix=='.csv':
  with p.open(encoding='utf-8-sig',newline='') as f:reader=csv.reader(f);rec['columns']=next(reader);rec['rows']=sum(1 for _ in reader)
 elif p.suffix=='.xlsx':
  from openpyxl import load_workbook
  wb=load_workbook(p,read_only=True,data_only=True);rec['sheets']={s.title:{'rows_including_header':s.max_row,'columns':s.max_column} for s in wb};wb.close()
 elif p.suffix=='.png':
  from PIL import Image
  with Image.open(p) as im:rec['dimensions']=im.size;rec['dpi']=im.info.get('dpi')
 records.append(rec)
(OUT/'file_inventory.json').write_text(json.dumps(records,indent=2))
cohort=pd.read_csv(P/'02_TABLES/main/Table1_cohort.csv');clusters=pd.read_csv(P/'02_TABLES/main/Table3_trajectory_clusters.csv');group=pd.read_csv(P/'02_TABLES/main/Table2_gene_groups.csv');conf=pd.read_csv(P/'02_TABLES/supplementary/TableS5_cluster_stability.csv');sensitivity=pd.read_csv(P/'02_TABLES/supplementary/TableS14_tier_cutoff_sensitivity.csv')
def table(frame):
 cols=list(frame.columns);rows=['| '+' | '.join(cols)+' |','| '+' | '.join('---' for _ in cols)+' |'];rows.extend('| '+' | '.join(str(v).replace('|','/') for v in row)+' |' for row in frame.fillna('').itertuples(index=False,name=None));return '\n'.join(rows)
intro='''# Current research inventory\n\nActive version:10 October2026, after researcher selection of the combined approach. Current source of truth is Paper1_Package plus canonical root result/data paths. Historical originals are preserved only in the recovery archive. No manuscript prose or new drug prediction is produced here.\n\n## Objectives and claim boundary\n\nThe final objective clarified by the researcher is drug repurposing to interrupt progression at different stages. Completed evidence supplies a stage-informed biomedical knowledge graph and association/trajectory/annotation/prioritisation analyses. No therapeutic efficacy, causal pathway, non-invasive stage prediction or external clinical validation is established.\n\nSource: researcher clarification; package01_OVERVIEW/Research objective;02_METHODS;04_LIMITATIONS.\n\n## Cohorts\n\nThe table below is raw-resource sample/patient/metadata coverage. Independent fibrosis analysis uses610 patients and demographic stage means327; raw staging covers668 biopsies. Disease axis216 patients,three varying studies. The repeat rule averages28 equal-stage pairs and discards the second biopsy in30 differing-stage pairs.\n\nSource:02_TABLES/main/Table1_cohort.csv and additive harmonisation/nodes_sample_clinical.csv; root biopsy_policy.py; correction decision ledger.\n\n'''
inventory=intro+table(cohort)+'\n\n## Methods, identifiers and integration\n\n'+(docs/'02_METHODS.md').read_text()+'\n\n## Current result groups\n\nSource:02_TABLES/main/Table2_gene_groups.csv.\n\n'+table(group)+'\n\n## Cluster profiles and confidence\n\nSources:Table3 andTableS5.\n\n'+table(clusters)+'\n\n'+table(conf)+'\n\n## Prioritisation sensitivity\n\nSource:TableS14. Tiers are administrative scores, not probability of validation.\n\n'+table(sensitivity)+'\n\n## Graph schema and current counts\n\nEight node types:Gene,Sample,Dataset,Disease,Drug,Pathway,BioProcess,Phenotype. Patient is a property, not a node. Fourteen relation types;126,244 nodes and35,132,831 relationships at corrected-run live verification. The final graph has8,044 progression links; curated relationships and raw expression values preserved; derived GSE193066 expression and five derived disease labels updated. Sources:canonical graph CSVs and final_combined_2026-10-10/graph_verification.json.\n\n## External source inventory\n\n'+(R/'docs/provenance/DATA_SOURCES.md').read_text()+'\n\n## Every package file\n\nTable counts exclude headers; workbook sheet rows include their headers. File presence does not prove independent validation.\n\n| File | Inspected size/count |\n|---|---|\n'
for rec in records:
 detail=f"{rec['bytes']} bytes"
 if 'rows'in rec:detail+=f"; {rec['rows']} rows"
 if 'dimensions'in rec:detail+=f"; {rec['dimensions']} pixels"
 if 'sheets'in rec:detail+='; '+', '.join(rec['sheets'])
 inventory+=f"| {rec['file']} | {detail} |\n"
(OUT/'research_inventory.md').write_text(inventory)
(OUT/'complete_workflow.md').write_text('''# Current completed workflow\n\nThe original data collection, parsing, ID mapping, crosswalk and OptimusKG integration are upstream inputs. The final combined approach changes five derived disease labels and the GSE193066 expression transformation before discovery. The shared biopsy correction begins at discovery and propagates through patient summaries,Tasks1–5 and progression-edge export. Data/expression_analysis_core was recovered read-only; baseline discovery reproduced original statistics before correction. All affected steps were rerun before active replacement.\n\n'''+(docs/'02_METHODS.md').read_text()+'''\n\n## Chronology and implementation versus plans\n\nAugust–September2026: original harmonisation, graph expansion, OptimusKG/zero-retention, progression discovery and mentor exports. October6–9: Tasks1–5, package, clinical/repeat corrections and graph reconciliation. October10: unified biopsy rule, full-universe LOSO, affected reruns, verified graph-link update and promotion to canonical files. Final combined commands/timings are in final_combined_2026-10-10/analysis_run_status.json; the factorial comparison is retained there as evidence. The researcher chose the combined result and removed the alternative run folders. Original detailed session/commit interpretation is in the archived first-stage audit.\n\nResearcher decisions: graph for downstream drug repurposing; average same-stage/otherwise biopsy1. Implemented procedures: current root scripts and package02_METHODS. Planned/failed work: successful drug-link model,causal validation,clinical efficacy,RAG/chatbot and liver-only trimming are not completed outputs. Top25/top12 selection rules remained unchanged; AST checks are saved in selection_logic_verification.json.\n''')
(OUT/'results_evidence_map.md').write_text('''# Current claim-to-evidence map\n\n| Finding | Source/locator | Manuscript placement | Boundary |\n|---|---|---|---|\n| Eight cohorts,1085 samples/1027 patient IDs;610 independent staged patients | Table1/clinical table;biopsy decision ledger | Methods,cohort Results,Figure1 | Raw resource counts differ from independent analysis n |\n| Selected genes3845 fibrosis,4199 disease,1822 shared,6222 union | progression tables,q<.05 AND unanimity;Table2 | Results,Figures2–3 | Correlation/selection,not diagnosis or causal progression |\n| Five cluster shapes857/1367/226/397/998 | Table3;TableS2/S5;Task2 outputs | Results,Figures4–6,S1 | Per-gene confidence/denominator and conditional matching matter |\n| Adjacent contrasts and matched refits | Table4,TableS6/S7;Task3 | Results,Figure7,S2 | Preselected gene set,cross-sectional;F4 underpowered |\n| Current group/core enrichment | Table5,TableS8–S10;Task4 all/per-run tables | Results,Figure8,supplementary panels | Read current core test status and per-group enrichment; annotations overlap |\n|447 Tier1 and23 balanced candidates | Table6(confidence added),TableS11/S12,S14–S18 | Results/Methods,shortlist table | Complementary scoring,not validated drug targets |\n|442/447 significant all five LOSO;247/447 retain effect bar | TableS13 plus all-eligible run table | Results/supplement robustness | Full-family correction;selected-set internal robustness,not external/nested validation |\n|12 mechanisms,42 genes,154 edges,4 shortlist genes shown | TableS19 sheets1–6;Figure9 | Results/annotation network | Gene→Pathway and Gene→BioProcess are separate links;not causal mechanisms |\n| Corrected live graph links | graph_nodes andknowledge_layer matching edge CSVs;graph update verification | Resource Results,data/code availability | Only patient-derived edges updated;raw/curated graph preserved |\n\nIntroduction requires verified primary sources on liver disease,prognosis,modern nomenclature,clinical staging and comparable graphs. Current annotations are not a substitute for a literature review. Drug prediction and therapeutic validation belong to downstream work.\n\nFigures1–9 andS1–S21 are rebuilt/current. Empty enrichment panels explicitly distinguish tested-null from untested groups. Table6 includes confidence;TableS19 uses447 Tier1 rather than an old count in its sheet title. All displays still need final journal-size proof and biological interpretation before submission.\n\nCurrent numerical statistics:\n\n'''+(docs/'03_STATISTICS.md').read_text())
(OUT/'missing_information.md').write_text('# Remaining evidence questions\n\n'+(docs/'04_LIMITATIONS.md').read_text()+'''\n\n## Missing assets and next review\n\nOriginal raw GEO/series matrices,HGNC release metadata,OptimusKG original parquet and full53,993-gene expression export are not locally available. The recovered14,794-gene analysis core is sufficient for these analyses but cannot reconstruct/reload every raw graph measurement. Original mentor Word briefs/full JSONL tools and the source acquisition chain remain absent; archived transcripts are dated evidence.\n\nThe source search did not recover individual GSE130970 diagnoses. Five flagged samples are now unclassified; the remaining labels remain derived and require transparent reporting. GSE193066 linear RLE units are confirmed and preserved. Further biological interpretation/confounding and literature verification remain required. No manuscript prose has been drafted.\n\nResolved by correction: inconsistent biopsy aggregation and patient weights;selected-only LOSO BH;stale active CSVs/figures;incorrect active counts;duplicated progression-edge CSVs;missing independent-confidence column in Table6;misleading old filenames and active Word draft. Historical issues remain traceable in archives/previous_results_2026-10-10.tar.gz.\n''')
print('Current manuscript planning written; package files inventoried:',len(records))
